version: 0.2
phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - '**/*'
    base-directory: 'target/my-web-app'
  discard-paths: yes
